### ISSUE TITLE
 Extension doesn't work

### ISSUE THREAD

**Issue by CorayThan** [granttitus/crucibletracker-issues#1]
Hey, when I try to use your chrome extension it looks like I get the error:

```
inject.js:2 Uncaught ReferenceError: __REACT_DEVTOOLS_GLOBAL_HOOK__ is not defined
    at inject.js:2
    at inject.js:69
```

Seems like you have a reference to react dev tools that isn't available outside your dev environment or something?

**Comment by granttitus** [comment]
Thank you for writing this up. This issue should now be fixed.
